config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/myproducts', to: 'pages#myproducts'

  # terms and conditions
  get '/terms', to: 'pages#terms'
  get '/refund', to: 'pages#refund'

  resources :products do
    resources :orders, only: %i[new create]
  end

  resources :orders, only: %i[index show create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_one :review, through: :product

  PAY_METHOD = ['Efectivo', 'Tarjeta de crédito', 'Tarjeta de débito', 'Transferencia']

  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :pay_method, presence: true, inclusion: { in: PAY_METHOD, message: "Categoria invalida" }
  validates :address, presence: true, length: { minimum: 10 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :reviews
  belongs_to :user
  has_one_attached :photo
  # crear un imput campo en la vista del form
  # en show: Product.photo (@product.photo)
  # <%= cl_image_tag @product.photo.key, alt: "Logo", style:"height:80px", class:"" %>

  CATEGORIES = %w[Polos Poleras Camisas Jeans Vestidos Shorts Pijamas Gorros Casacas Chompas]

  validates :name, presence: true, length: { minimum: 4 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :category, presence: true, inclusion: { in: CATEGORIES, message: "Categoria invalida" }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :photo, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :content, presence: true, length: { minimum: 6 }
  validates :rating, presence: true, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_many :orders
  validates :nickname, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(order_params)
    @order.product = @product
    @order.user = current_user
    @order.reviewed = false
    if @order.save
      redirect_to orders_path, notice: "Compra realizada con exito"
      @product.stock -= 1
      @product.save
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:address, :pay_method)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def myproducts
    @products = Product.where(user_id: current_user.id)
    @orders = []
    @products.each do |product|
      if product.orders.present?
        @orders += product.orders
      end
    end
  end

  def terms
  end

  def refund
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_product, only: %i[edit update show]

  def index
    if params[:search].present?
      if params[:search][:query].empty?
        @products = user_signed_in? ? Product.all.where("user_id != ?", current_user.id.to_s) : Product.all
      else
        sql_query_user = " \
          name iLIKE :query AND user_id <> :user_id \
          OR category iLIKE :query AND user_id <> :user_id \
          OR description iLIKE :query AND user_id <> :user_id \
        "

        sql_query_visitor = " \
          name iLIKE :query \
          OR category iLIKE :query \
          OR description iLIKE :query \
        "
        if user_signed_in?
          sql_query = sql_query_user
          id = current_user.id.to_s
        else
          sql_query = sql_query_visitor
          id = ""
        end

        @products = Product.where(sql_query, query: "%#{params[:search][:query]}%", user_id: id)
      end
    end
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :category, :price, :stock, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_order, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.product = @order.product

    if @review.save
      @order.reviewed = true
      @order.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
   <main>
      <%= render 'shared/navbar' %>
      <%# <%= render 'shared/flashes' %>
      <%= yield %>
   </main>
   <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container p-5">

  <div class="text-center mb-5" >
    <h3 class="text-secondary"> <strong> Mis compras </strong> </h3>
  </div>

  <%= render 'shared/flashes' %>

  <div class="container-cards">
    <% @orders.each do |order| %>
    <div class="card-products">
      <%= cl_image_tag order.product.photo.key, alt: "foto de producto", class: "img-order" %>
      <div class="card-product-infos w-100">
        <h2 class="m-0"> <strong> Producto : <%= order.product.name.capitalize %> </strong> </h2>
        <p class="m-0"> <small> Fecha de compra: <%= order.created_at.localtime.strftime("%d/%m/%Y %I:%M %p") %> </small> </p>
        <p class="mt-2">Direccion de envio: <%= order.address %></p>
        <p class="mb-2"> Metodo de pago: <%= order.pay_method %>  </p>
        <div class="container-selling">
          <div>
            <p class="selling-item"> <small> Vendido por: <%= order.user.nickname %> </small> </p>
          </div>
          <div>
            <% if order.reviewed %>
              <p id="review-item" class="font-weight-bold selling-item2">Review completo</p>
            <% else %>
              <p id="review-item2" class="badge badge-info selling-item2"><%= link_to "Dejar Review", new_order_review_path(order), class: "text-body" %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div  class="text-right mt-5"><%= link_to "Cambios y Devoluciones", refund_path, id:"change" %></div>
</div>

app/views/orders/new.html.erb
<div class="container py-5 px-0">
  <div class="container bg-white p-5 w-50 rounded">
    <h1>Formulario de compra</h1>
    <%= simple_form_for [@product, @order], url: product_orders_path do |f| %>
      <%= f.input :address, label: "Dirección" %>
      <%= f.input :pay_method, collection: Order::PAY_METHOD, label: "Método de pago" %>
      <div class="d-flex justify-content-center">
        <%= f.submit value: "Confirmar compra", class: "btn btn-dark mt-5 btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<% if notice %>
  <div class="alert sign-in alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<div>
  <div class="banner mb-5 h-100" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1525562723836-dca67a71d5f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80);">
    <div class="container text-center">
      <h1><span id="banner-typed-text"></span></h1>
    </div>
  </div>
</div>

<div class="container text-center my-3 py-4 px-2">
    <div class="py-1 mb-3">
      <h2 class="d-block p-2 my-4 text-center fw-bolder"> <strong> Discover our clothes </strong> </h2>
    </div class="py-2">
    <p class="text-left mb-0">For men</p>
    <div class="row mx-auto my-auto">
        <div id="recipeCarousel" class="carousel slide w-100" data-ride="carousel">
            <div class="carousel-inner w-100" role="listbox">
                <div class="carousel-item active">
                    <div class="col-md-4">
                        <div class="card card-body mt-0">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1564859227552-81fde4a1df0b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80)">
                              <a href="/products?search%5Bquery%5D=polos" class="stretched-link">Polos</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1490427712608-588e68359dbd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
                              <a href="/products?search%5Bquery%5D=jeans" class="stretched-link">Jeans</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1606724003282-df6ecad297ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=773&q=80)">
                              <a href="/products?search%5Bquery%5D=camisas" class="stretched-link">Camisas</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1610901157620-340856d0a50f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80)">
                              <a href="/products?search%5Bquery%5D=chompas" class="stretched-link">Chompas</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                           <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1532582788350-ac25f2099fde?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80)">
                              <a href="/products?search%5Bquery%5D=shorts" class="stretched-link">Shorts</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev w-auto" href="#recipeCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next w-auto" href="#recipeCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <p class="text-left mt-5 mb-0">For women</p>
    <div class="row mx-auto my-auto">
        <div id="recipeCarousel2" class="carousel slide w-100" data-ride="carousel">
            <div class="carousel-inner w-100" role="listbox">
                <div class="carrousel carousel-item active">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1496747611176-843222e1e57c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=873&q=80)">
                              <a href="/products?search%5Bquery%5D=vestidos" class="stretched-link">Vestidos</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1551715789-d7b5cfccd1c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
                              <a href="/products?search%5Bquery%5D=jeans" class="stretched-link">Jeans</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1582142306909-195724d33ffc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
                              <a href="/products?search%5Bquery%5D=faldas" class="stretched-link">Faldas</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                            <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1623197326553-ef361f80e894?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=847&q=80)">
                              <a href="/products?search%5Bquery%5D=chompas" class="stretched-link">Chompas</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="col-md-4">
                        <div class="card card-body">
                           <div class="img-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1496360938681-9a918bfabc66?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80)">
                              <a href="/products?search%5Bquery%5D=shorts" class="stretched-link">Shorts</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev w-auto" href="#recipeCarousel2" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next w-auto" href="#recipeCarousel2" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

app/views/pages/myproducts.html.erb
<div class="container py-5">

  <h2 class="border-bottom mb-3"><strong class="text-secondary"> Tus productos publicados </strong></h2>
  <%# <div class="col-12 col-sm-8 col-md-6 col-lg-4"> %>
  <div class="cards">
    <% @products.each do |product| %>
          <div class="card card-product border-0">
            <div class="card-img-overlay d-flex justify-content-end">
              <a href="#" class="card-link btn-like">
                <i class="far fa-heart text-primary"></i>
              </a>
            </div>
            <div class="card-body">
              <div class="img-container"><%= image_tag (cl_image_path product.photo.key), class: "card-img" %></div>
              <div class="card-info">
                <small class="details text-muted">Por <%= product.user.nickname %></small>
                <h4 class="card-title"><%= product.name.length > 23 ? "#{product.name[0..23].capitalize}..." : product.name.capitalize %></h4>
                <p class="card-text text-muted"><%= product.description.length > 50 ? "#{product.description[0..50]}..." : product.description %></p>
              </div>
              <div class="buy d-flex justify-content-between align-items-center">
                <h6 class="stock text-muted m-0">Stock: <%= product.stock %></h6>
                <h5 class="font-weight-bold">S/. <%= product.price%></h5>
              </div>

              <div class="d-flex align-items-center">
                <%= link_to 'Editar', edit_product_path(product), class:"btn btn-dark btn-edit" %>
              </div>
            </div>
          </div>
    <% end %>
  </div>
  <%# </div> %>




  <h2 class="my-4 py-2 border-bottom mb-3 mt-5"><strong class="text-secondary"> Tus Productos vendidos </strong></h2>
  <%# <div class="col-12 col-sm-8 col-md-6 col-lg-4"> %>
  <div class="container-cards">
    <% @orders.each do |order| %>
    <div class="card-products">
      <%= cl_image_tag order.product.photo.key, alt: "foto de producto", class: "img-order" %>
      <div class="card-product-infos w-100">
        <h2><%= order.product.name.capitalize %></h2>
        <p>Fecha de compra: <%= order.created_at.localtime.strftime("%d/%m/%Y %I:%M %p") %></p>
        <p>Direccion de envio: <%= order.address %></p>
        <p>Metodo de pago: <%= order.pay_method %></p>
        <div class="container-selling">
          <div>
            <p class="selling-item">Comprador: <%= order.user.nickname %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/pages/refund.html.erb
<div class="container">
 <h1 class="py-4">Cambios y Devoluciones</h1>
 <h3 class="py-4">Por favor tome en cuenta lo siguiente:</h3>
 <p>
   Para cambiar tu producto, hazlo directamente con el vendedor mostrando tu boleta.
   Si tu producto fue vendido por nosotros, acércate a cualquiera de sus tiendas con tu boleta.
   Si quieres saber más, revisa nuestras nuevas Políticas de cambios y devoluciones.
 </p>
 <br>
 <a href="/terms">Políticas de cambios y devoluciones.</a> 
 <br>
 <br>
 <p>Cambia o devuelve tu producto en la ubicacion del proveedor. Encuentra la boleta en tu correo y muéstrala desde el celular.</p>
 
   
 
</div>

app/views/products/edit.html.erb
<div class="container py-5 px-0">

  <div class="container">

    <div class="container bg-white p-5 w-75 rounded">
      <h2> <strong>Editar producto </strong> </h2>
      <%= simple_form_for(@product) do |f| %>
        <%= f.input :name, label: "Nombre" %>
        <%= f.input :description, label: "Descripcion" %>
        <%= f.input :category, label: "Categoria", collection: Product::CATEGORIES, error: "Tienes que seleccionar una categoria" %>
        <%= f.input :price, label: "Precio en Nuevos Soles S/." %>
        <%= f.input :stock, label: "Cantidad" %>
        <%= f.input :photo, as: :file, label: "Fotografia" %>
        <div class="d-flex justify-content-center ">
          <%= f.submit value: "Editar producto", class: "btn btn-dark mt-5 btn-lg" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container py-5 px-0">

  <div class="container">
    
    <div class="container bg-white p-5 w-75 rounded">
      <h2> <strong> Añadir producto </strong> </h2>
      <%= simple_form_for(@product) do |f| %>
        <%= f.input :name, label: "Nombre" %>
        <%= f.input :description, label: "Descripcion" %>
        <%= f.input :category, label: "Categoria", collection: Product::CATEGORIES, error: "Tienes que seleccionar una categoria" %>
        <%= f.input :price, label: "Precio en Nuevos Soles S/." %>
        <%= f.input :stock, label: "Cantidad" %>
        <%= f.input :photo, label: "Fotografia" ,as: :file %>
        <div class="d-flex justify-content-center ">
          <%= f.submit value: "Añadir producto", class: "btn btn-dark mt-5 btn-lg" %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
  <div class="container">
    <div class="p-0 my-5 d-flex justify-content-between bg-white row product-size" >
      <div class="container p-0 col-md-8">
        <%= cl_image_tag @product.photo.key, alt: "", class: "card-img-top product-show" %>
      </div>

      <div class="container p-5 col-md-4">
        <div>
          <p class="badge badge-info justify-content-end"> <small><%= @product.category %> </small></p>
          <h3> <strong> <%= @product.name %> </strong> </h3>
          <p class="text-secondary"><%= @product.description %></p>
          <p class="text-secondary m-0">Stock: <%= @product.stock %></p>
          <p class="text-secondary m-0">Color: <%= "White" %></p>
        </div>
        <h2 class="card-trip-pricing py-4 m-0"> <strong> S/. <%= @product.price %> </strong></h2>


        <form class="pt-4">
          <div class="form-row">
            <div class="form-group col-md-6">
              <select id="inputState" class="form-control">
                <option selected>Talla</option>
                <option>XS</option>
                <option>S</option>
                <option>M</option>
                <option>L</option>
                <option>XL</option>
              </select>
            </div>

            <div class="form-group col-md-6">
              <select id="inputState" class="form-control">
                <option selected>Escoge</option>
                <option>...</option>
              </select>
            </div>
            
            <div class="form-group col-md-12 text-center">
              <% if @product.stock > 0 %>
              <%= link_to "Comprar", new_product_order_path(@product), class:"btn btn-flat" %>
              <% else %>
              <%= link_to "Fuera de stock", "#", class:"btn btn-flat disabled" %>
              <% end %>
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>

  
  <div class="container">
    <h3>Reviews</h3>
    <% if @product.reviews.present? %>
      <% x = 1 %>
      <% @product.reviews.each do |review| %>          
          <div class="bg-white p-4 border">
            <h6> <strong> Usuario <%= x %> </strong> </h6>
            <div class="card-title m-0"> <em>"<%= review.content %>"</em> </div>
            <div>Rating: <%= review.rating %></div>
          </div>
          <% x += 1 %> 
      <% end %>
    <% else %>
      <p>No hay reviews disponibles</p>
    <% end %>
  </div>

app/views/reviews/new.html.erb
<div class="container py-5 px-0">
  <div class="container">
    <div class="container bg-white p-5 w-75 rounded">
      <h2><strong>Nuevo review</strong></h2>
      <%= simple_form_for [@order, @review] do |f| %>
        <%= f.input :content, label: "Comentario" %>
        <%= f.input :rating, label: "Rating (Entre 1 y 5)" %>
        <div class="d-flex justify-content-center">
          <%= f.submit value: "Enviar review", class: "btn btn-dark mt-5 btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light sticky-top">
  <a class="navbar-brand text-secondary" href="/"> <strong> MEGACLOTHES </strong> </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end mr-4">
    <%= simple_form_for(:search, method: :get, url: "/products", html: { class: "form-inline" } ) do |f| %>
      <%= f.input :query, placeholder: "Buscar productos", label: false, html: { required: true } %>
      <%= button_tag(type: 'submit', class: "ml-1 btn btn-light", name: nil) do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent-4">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Añadir producto", new_product_path, class: "nav-link text-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mis compras", orders_path, class: "nav-link text-secondary" %>
        </li>
        <li class="nav-item dropdown", style = "cursor: pointer;">
          <a class="nav-link dropdown-toggle text-secondary" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i> <%= current_user.nickname %> </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
            <%= link_to "Mi cuenta", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Mis productos", myproducts_path, class: "dropdown-item" %>
            <%= link_to "Cerrar sesion",  destroy_user_session_path, method: "delete", class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Registrarse", new_user_registration_path, class: "nav-link text-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Iniciar sesion",  new_user_session_path, class: "nav-link text-secondary" %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>